/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Reservation = IDL.Record({
  'id' : IDL.Nat,
  'service' : IDL.Text,
  'name' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAvailableSlots' : IDL.Func([], [IDL.Nat], ['query']),
  'getReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
  'makeReservation' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'resetSlots' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Reservation = IDL.Record({
    'id' : IDL.Nat,
    'service' : IDL.Text,
    'name' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getAvailableSlots' : IDL.Func([], [IDL.Nat], ['query']),
    'getReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
    'makeReservation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'resetSlots' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };